spring:
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      msTechnician:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s

logging:
  level:
    root: INFO
