name: ms-payment-dev

version: "3.9"

services:
  mysql-payment-dev:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_payment
    ports:
      - "3316:3306"
    volumes:
      - mysql_payment_dev_data:/var/lib/mysql

volumes:
  mysql_payment_dev_data:
